version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: anbui
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pgtest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "anbui", "-d", "pgtest"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - network

  migrate:
    image: migrate/migrate:v4.15.2
    container_name: migrate
    # profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://anbui:1234@db:5432/pgtest?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      - db
    restart: on-failure
    networks:
      - network

#  backend:
#    build:
#      context: .
#      dockerfile: ./cmd/myapp/Dockerfile
#    container_name: backend
#    environment:
#      POSTGRES_HOST: postgres
#      POSTGRES_USER: anbui
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: pgtest
#      POSTGRES_PORT: 5432
#    ports:
#      - '8001:8001'
#    restart: always
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - network

#  library:
#     build:
#       context: ./docker
#       dockerfile: Dockerfile.library
#     image: postgres:9.5
#     container_name: library
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_USER: anbui
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: pgtest
#       POSTGRES_PORT: 5432
#     volumes:
#       - ./data/library:/library
#     depends_on:
#       - db
#     tty: true
#     networks:
#       - network

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
#    container_name: elasticsearch
#    restart: always
#    environment:
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - 9200:9200
#      - 9300:9300
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#    networks:
#      - network

networks:
  network:
