version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: anbui
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pgtest
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: ./cmd/myapp/Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: anbui
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pgtest
      POSTGRES_PORT: 5432
    ports:
      - '8001:8001'