version: '3.8'
services:
  db:
    image: postgres:9.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: anbui
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pgtest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: ./cmd/myapp/Dockerfile
    container_name: backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: anbui
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pgtest
      POSTGRES_PORT: 5432
    ports:
      - '8001:8001'
    restart: always
    depends_on:
      - db
    networks:
      - network

  migrate:
    image: migrate/migrate:v4.15.2
    container_name: migrate
    # profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://anbui:1234@db:5432/pgtest?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      - db
    restart: on-failure
    networks:
      - network
networks:
  network:
